version: '3.9'
services:
  app:
    container_name: golang_container
    environment:
      - POSTGRES_DSN=${DB_DRIVER}://${DB_USER}:@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    tty: true
    build: .
    ports:
      - 8000:8080
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - internal

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '1234:5432'
    networks:
      - internal

# Networks to be created to facilitate communication between containers
networks:
  internal:
    driver: bridge
